version: '3.7'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: int-api

  app:
    build: ./app
    ports:
      - "3000:80"
    container_name: int-app

  # To test mongodb locally
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: int-db